# Generated by Django 5.2.4 on 2025-07-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
