# Generated by Django 5.2.4 on 2025-08-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
